import type {Metadata} from "next";
import "./globals.css";
import Sidebar from '@/components/layout/Sidebar'
import BottomNavigation from '@/components/layout/BottomNavigation'
import {Public_Sans} from 'next/font/google'
import ReactQueryProvider from '../util/ReactQueryProvider'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const sans = Public_Sans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={`${sans.variable} font-sans`}>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon"/>
        <div className="flex flex-col lg:flex-row min-h-screen">
            {/* Desktop Sidebar */}
            <aside className="hidden xl:block h-dvh shrink-0">
                <Sidebar/>
            </aside>
            {/* Main Content */}
            <main className="w-full max-w-[1440px] mx-auto px-4 md:px-10 pt-8 pb-20 md:pb-32 xl:pb-8 xl:h-dvh">
                <ReactQueryProvider>
                    {children}
                </ReactQueryProvider>
            </main>
            {/* Mobile Navigation */}
            <nav className="block xl:hidden basis-full w-full fixed bottom-0">
                <BottomNavigation/>
            </nav>
        </div>
        </body>
        </html>
    );
}
